management:
  endpoints:
    web:
      exposure:
        include: health, metrics, loggers
  endpoint:
    health:
      probes:
        enabled: true
      group:
        liveness:
          include: "livenessState"
        readiness:
          include: "readinessState"
      show-details: always

spring:
  datasource:
    username: cloudmobility
    password: mysecretpassword
    url: jdbc:postgresql://localhost:5450/cloudmobilityDB?currentSchema=privatehospital
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    baseline-on-migrate: ${BASELINE_ON_MIGRATE:true}
    clean-disabled: true
    schemas: [privatehospital]

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    display-request-duration: true
    groups-order: desc
    operations-sorter: alpha
    path: ''
  group-configs:
    -   group: Patient
        paths-to-match:
          - /**/**/patient/**
    - group: Doctor
      paths-to-match:
        - /**/**/doctor/**

logging:
  level:
    ROOT: INFO
    com.example.cloudmobilityprivatehospital: INFO
