services:
  cloud-mobility-postgresql:
    image: postgres
    volumes:
      - ../resources/db/initscripts/:/docker-entrypoint-initdb.d/
    environment:
      POSTGRES_DB: cloudmobilityDB
      POSTGRES_USER: cloudmobility
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - 5432:5432
  cloud-mobility-private-hospital:
    build:
      context: ../../../
    depends_on: [cloud-mobility-postgresql]
    command: mvn clean install
    ports:
      - 8080:8080
