services:
  cloud-mobility-postgresql:
    image: postgres
    volumes:
      - ../resources/db/initscripts/:/docker-entrypoint-initdb.d/
    environment:
      POSTGRES_DB: cloudmobilityDB
      POSTGRES_USER: cloudmobility
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - 5450:5432